### PR TITLE
Fix to issue SONARCLIPS-403

### PR DESCRIPTION
**Pull request by Hemantkumar-Chigadani**
Sonar marker-issues deleting/fetching on analysis executed by SynchronizeAllIssuesJob and SynchronizeIssuesJob is done lazily now. 
Logging the failures/exceptions to debug level instead of failure pop-ups when analysis is not forced by user Example Open a source file in the editor or Auto-Sonar-builder[future concept].

Cause: When Sonar full analysis is called on a project when SonarQube server is not reachable, will delete the issue markers from the project & then fails to fetch the issues from the SonarQube server. Even SynchronizeIssuesJob fails to load the issues from SonarQube server when a file is opened hen SonarQube server is not reachable, pops up the dialogue each time file is opened from the project.

### CODE REVIEW

**Comment by henryju** [comment]
I have already worked on this issue. Please rebase your branch on master to get latest changes. Also please configure Eclipse formatter according to our coding style (see https://github.com/SonarSource/sonar-developer-toolset). Thanks

**Comment by Hemantkumar-Chigadani** [comment]
I have tried to merge/rebase existing branch to master, but I think it would not make life easy for the comparison. 
I have created a new branch [up to date with master] has very few lines of minor changes but useful ones in SynchronizeAllIssuesJob.
1) Server offline check in advance
2) Removed duplicate call to deleteIssuesMarkers 

https://github.com/Hemantkumar-Chigadani/sonar-eclipse/tree/Fix_issue_SONARCLIPS-403_1

I hope, you will be able to accept them. Thanks.

**Comment by henryju** [comment]
Can you submit a new pull request for this new branch so that I can easily see the modifications? Thanks.

**Comment by Hemantkumar-Chigadani** [comment]
Please look for new pull request #18. Thanks.

**Comment by henryju** [comment]
So I'm closing this P/R since I feel this is already in a better shape in master.

**Pull request closed without merging**
